export default {
  // Department types
  SET_DEPARTMENTS: "SET_DEPARTMENT",
  ADD_DEPARTMENT: "ADD_DEPARTMENT",
  UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",

  // Designation types
  SET_DESIGNATIONS: "SET_DESIGNATION",
  ADD_DESIGNATION: "ADD_DESIGNATION",
  UPDATE_DESIGNATION: "UPDATE_DESIGNATION",

  // Personal Info
  SET_PERSONAL_INFO: "SET_PERSONAL_INFO",
  UPDATE_PERSONAL_INFO: "UPDATE_PERSONAL_INFO",

  // Employee types
  SET_EMPLOYEES: "SET_EMPLOYEE",
  ADD_EMPLOYEE: "ADD_EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",

  // Misc types
  SET_NOTIF_SNACKBAR: "SET_NOTIF_SNACKBAR",
  SET_MESSAGE_MODAL: "SET_MESSAGE_MODAL",
  SET_CURRENT: "SET_CURRENT",
  SET_LOADING: "SET_LOADING",
  SET_DROPDOWN: "SET_DROPDOWN"
};
