export default {
  SET_DEPARTMENT: "SET_DEPARTMENT",
  ADD_DEPARTMENT: "ADD_DEPARTMENT",
  UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",
  SET_LOADING: "SET_LOADING",

  SET_NOTIF_SNACKBAR: "SET_NOTIF_SNACKBAR",
  SET_MESSAGE_MODAL: "SET_MESSAGE_MODAL"
};
