export default {
  // Department types
  SET_DEPARTMENTS: "SET_DEPARTMENT",
  ADD_DEPARTMENT: "ADD_DEPARTMENT",
  UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",

  // Designation types
  SET_DESIGNATIONS: "SET_DESIGNATION",
  ADD_DESIGNATION: "ADD_DESIGNATION",
  UPDATE_DESIGNATION: "UPDATE_DESIGNATION",

  // Misc types
  SET_NOTIF_SNACKBAR: "SET_NOTIF_SNACKBAR",
  SET_MESSAGE_MODAL: "SET_MESSAGE_MODAL",
  SET_CURRENT: "SET_CURRENT",
  SET_LOADING: "SET_LOADING",
  SET_DROPDOWN: "SET_DROPDOWN"
};
